language: python

sudo: required

matrix:
  fast_finish: true
  include:
    - dist: trusty
      python: "2.7"
      env: COQ_VERSION="master"   COQ_PACKAGE="coq"                            PPA="ppa:jgross-h/coq-master-daily"
    - dist: trusty
      python: "2.7"
      env: COQ_VERSION="v8.8"     COQ_PACKAGE="coq"                            PPA="ppa:jgross-h/coq-8.8-daily"
    - dist: trusty
      python: "2.7"
      env: COQ_VERSION="v8.7"     COQ_PACKAGE="coq"                            PPA="ppa:jgross-h/coq-8.7-daily"
    - dist: trusty
      python: "2.7"
      env: COQ_VERSION="v8.6"     COQ_PACKAGE="coq"                            PPA="ppa:jgross-h/coq-8.6-daily"
    - dist: trusty
      python: "2.7"
      env: COQ_VERSION="v8.5"     COQ_PACKAGE="coq"                            PPA="ppa:jgross-h/coq-8.5-daily"
    - dist: trusty
      python: "2.7"
      env: COQ_VERSION="8.8.1"    COQ_PACKAGE="coq-8.8.1"                      PPA="ppa:jgross-h/many-coq-versions"
    - dist: trusty
      python: "2.7"
      env: COQ_VERSION="8.7.2"    COQ_PACKAGE="coq-8.7.2"                      PPA="ppa:jgross-h/many-coq-versions"
    - dist: trusty
      python: "2.7"
      env: COQ_VERSION="8.6.1"    COQ_PACKAGE="coq-8.6.1"                      PPA="ppa:jgross-h/many-coq-versions"
    - dist: trusty
      python: "2.7"
      env: COQ_VERSION="8.5pl3"   COQ_PACKAGE="coq-8.5pl3 libcoq-8.5pl3-ocaml" PPA="ppa:jgross-h/many-coq-versions"
    - dist: precise
      python: "2.7"
      env: COQ_VERSION="8.4pl6"   COQ_PACKAGE="coq-8.4pl6 libcoq-ocaml-8.4pl6" PPA="ppa:jgross-h/many-coq-versions-ocaml-3"
  allow_failures:
    - env: COQ_VERSION="v8.5"     COQ_PACKAGE="coq"                            PPA="ppa:jgross-h/coq-8.5-daily"
    - env: COQ_VERSION="v8.6"     COQ_PACKAGE="coq"                            PPA="ppa:jgross-h/coq-8.6-daily"
    - env: COQ_VERSION="v8.7"     COQ_PACKAGE="coq"                            PPA="ppa:jgross-h/coq-8.7-daily"
    - env: COQ_VERSION="v8.8"     COQ_PACKAGE="coq"                            PPA="ppa:jgross-h/coq-8.8-daily"
    - env: COQ_VERSION="master"   COQ_PACKAGE="coq"                            PPA="ppa:jgross-h/coq-master-daily"

before_install:
  - if [ ! -z "$PPA" ]; then sudo add-apt-repository "$PPA" -y; fi
  - travis_retry ./etc/sudo-apt-get-update.sh -q
  - travis_retry sudo apt-get install $COQ_PACKAGE -y

script: make has-all-tests && make check CAT_ALL_LOGS=1
