# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI (docker)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        coq-version: ['dev', '8.15', '8.14', '8.13', '8.12', '8.11', '8.10', '8.9', '8.8', '8.7', '8.6', '8.5', '8.4']
        ocaml-version: ['default']

    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.coq-version }}-${{ matrix.ocaml-version }}-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v4
    - uses: coq-community/docker-coq-action@v1
      with:
        coq_version: ${{ matrix.coq-version }}
        ocaml_version: ${{ matrix.ocaml-version }}
        custom_script: |
          sudo chmod -R a+rw .
          echo '::group::install general dependencies'
          sudo apt-get update -y
          sudo apt-get install -y python3
          eval $(opam env)
          echo '::endgroup::'
          echo '::group::make print-support'
          make print-support PYTHON=python3
          echo '::endgroup::'
          make check PYTHON=python3 CAT_ALL_LOGS=1


  check-all-docker:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
    - run: echo 'The triggering workflow passed'
      if: ${{ needs.build.result == 'success' }}
    - run: echo 'The triggering workflow failed' && false
      if: ${{ needs.build.result != 'success' }}
